#!/bin/sh

set -euo pipefail

echo "building quorum-aws locally"
stack setup
stack build

echo "building quorum-aws for AWS"
docker build -t quorum-aws .

echo "building quorum"
docker build -t quorum ./dependencies/quorum

echo "building constellation"
docker build -t constellation -f ./dependencies/constellation/build-ubuntu.dockerfile --build-arg DISTRO_VERSION=xenial ./dependencies/constellation

echo "done building packages"
